//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\10482\Desktop\ZD\tools\ZD_StraightLifterReview.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 10482
//              Version: NX 2306
//              Date: 07-22-2026  (Format: mm-dd-yyyy)
//              Time: 11:03
//
//==============================================================================

#ifndef ZD_STRAIGHTLIFTERREVIEW_H_INCLUDED
#define ZD_STRAIGHTLIFTERREVIEW_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <string>
#include <vector>
#include <utility>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_RadiusDimension.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/Face.hxx>

//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: BodyRules
//------------------------------------------------------------------------------
#define                           BodyRules_SingleBody (1 << 0);
#define                        BodyRules_FeatureBodies (1 << 1);
#define                        BodyRules_BodiesinGroup (1 << 2);
#define                                 BodyRules_相切片体 (1 << 4);
#define                                 BodyRules_相邻片体 (1 << 5);
#define                                 BodyRules_相连片体 (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
#define        SnapPointTypesOnByDefault_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport ZD_StraightLifterReview
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    ZD_StraightLifterReview();
    ~ZD_StraightLifterReview();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the ZD_StraightLifterReview.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* object_group;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* body_select;// Block type: Body Collector
    NXOpen::BlockStyler::Group* standard_group;// Block type: Group
    NXOpen::BlockStyler::RadiusDimension* radius_dim0;// Block type: Radius Dim

    std::vector<NXOpen::Body*> GetSelectedBodies() const;
    double GetRadiusLimit() const;
    void ReviewBody(NXOpen::Body* body, double radiusLimit);
    void HighlightFace(NXOpen::Face* face);
    void ClearReviewDisplay();
    void CommitReviewDisplay();
    void WriteReport(const std::vector<std::string>& lines) const;

    std::vector<std::pair<NXOpen::Face*, int> > highlightedFaces;
    std::vector<NXOpen::Body*> highlightedBodies;
    static double AngleToZDegrees(double normalZ);
    
};
#endif //ZD_STRAIGHTLIFTERREVIEW_H_INCLUDED



