//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\10482\Desktop\ZD\tools\ZD_StraightLifterReview.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 10482
//              Version: NX 2306
//              Date: 07-22-2026  (Format: mm-dd-yyyy)
//              Time: 11:03 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "ZD_StraightLifterReview.hpp"
#include <uf_modl.h>
#include <cmath>
#include <iomanip>
#include <sstream>
#include <algorithm>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/ModelingViewCollection.hxx>
#include <NXOpen/ModelingView.hxx>
#include <NXOpen/View.hxx>
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(ZD_StraightLifterReview::theSession) = NULL;
UI *(ZD_StraightLifterReview::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
ZD_StraightLifterReview::ZD_StraightLifterReview()
{
    try
    {
        // Initialize the NX Open C++ API environment
        ZD_StraightLifterReview::theSession = NXOpen::Session::GetSession();
        ZD_StraightLifterReview::theUI = UI::GetUI();
        theDlxFileName = "C:\\Users\\10482\\Desktop\\ZD\\tools\\ZD_StraightLifterReview.dlx";
        theDialog = ZD_StraightLifterReview::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &ZD_StraightLifterReview::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &ZD_StraightLifterReview::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &ZD_StraightLifterReview::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &ZD_StraightLifterReview::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &ZD_StraightLifterReview::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
ZD_StraightLifterReview::~ZD_StraightLifterReview()
{
    ClearReviewDisplay();
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    ZD_StraightLifterReview *theZD_StraightLifterReview = NULL;
    try
    {
        theZD_StraightLifterReview = new ZD_StraightLifterReview();
        // The following method shows the dialog immediately
        theZD_StraightLifterReview->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theZD_StraightLifterReview != NULL)
    {
        delete theZD_StraightLifterReview;
        theZD_StraightLifterReview = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        // 插件不保留会话外资源，无需清理。
    }
    catch(exception& ex)
    {
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse ZD_StraightLifterReview::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void ZD_StraightLifterReview::initialize_cb()
{
    try
    {
        object_group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("object_group"));
        body_select = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("body_select"));
        standard_group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("standard_group"));
        radius_dim0 = dynamic_cast<NXOpen::BlockStyler::RadiusDimension*>(theDialog->TopBlock()->FindBlock("radius_dim0"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void ZD_StraightLifterReview::dialogShown_cb()
{
    try
    {
        // 对话框显示时不改变用户输入。
    }
    catch(exception& ex)
    {
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int ZD_StraightLifterReview::apply_cb()
{
    int errorCode = 0;
    try
    {
        ClearReviewDisplay();
        const std::vector<NXOpen::Body*> bodies = GetSelectedBodies();
        if (bodies.empty())
        {
            ZD_StraightLifterReview::theUI->NXMessageBox()->Show("直顶头审查", NXOpen::NXMessageBox::DialogTypeWarning, "请至少选择一个直顶头实体后再执行审查。");
            return 1;
        }

        const double radiusLimit = GetRadiusLimit();
        for (std::vector<NXOpen::Body*>::const_iterator it = bodies.begin(); it != bodies.end(); ++it)
            ReviewBody(*it, radiusLimit);
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
// 审查辅助函数
//------------------------------------------------------------------------------
std::vector<NXOpen::Body*> ZD_StraightLifterReview::GetSelectedBodies() const
{
    std::vector<NXOpen::Body*> bodies;
    if (body_select == NULL)
        return bodies;

    const std::vector<NXOpen::TaggedObject*> selected = body_select->GetSelectedObjects();
    for (std::vector<NXOpen::TaggedObject*>::const_iterator it = selected.begin(); it != selected.end(); ++it)
    {
        NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(*it);
        if (body != NULL)
            bodies.push_back(body);
    }
    return bodies;
}

double ZD_StraightLifterReview::GetRadiusLimit() const
{
    if (radius_dim0 == NULL)
        return 0.0;

    NXOpen::BlockStyler::PropertyList* properties = theDialog->GetBlockProperties("radius_dim0");
    const double value = properties->GetDouble("Value");
    delete properties;
    return (std::max)(0.0, value);
}

double ZD_StraightLifterReview::AngleToZDegrees(double normalZ)
{
    const double clamped = (std::max)(-1.0, (std::min)(1.0, std::abs(normalZ)));
    return std::asin(clamped) * 180.0 / 3.14159265358979323846;
}

void ZD_StraightLifterReview::HighlightFace(NXOpen::Face* face)
{
    if (face == NULL)
        return;

    for (std::vector<std::pair<NXOpen::Face*, int> >::const_iterator it = highlightedFaces.begin(); it != highlightedFaces.end(); ++it)
    {
        if (it->first == face)
            return;
    }

    highlightedFaces.push_back(std::make_pair(face, face->Color()));
    face->SetColor(186);
    face->RedisplayObject();
}

void ZD_StraightLifterReview::ClearReviewDisplay()
{
    for (std::vector<std::pair<NXOpen::Face*, int> >::const_iterator it = highlightedFaces.begin(); it != highlightedFaces.end(); ++it)
    {
        if (it->first != NULL)
        {
            it->first->SetColor(it->second);
            it->first->RedisplayObject();
        }
    }
    highlightedFaces.clear();

    for (std::vector<NXOpen::Body*>::const_iterator it = highlightedBodies.begin(); it != highlightedBodies.end(); ++it)
    {
        if (*it != NULL)
            (*it)->Unhighlight();
    }
    highlightedBodies.clear();
}

void ZD_StraightLifterReview::CommitReviewDisplay()
{
    // 点击确定后保留错误面红色，只取消高度错误实体的临时高亮。
    highlightedFaces.clear();
    for (std::vector<NXOpen::Body*>::const_iterator it = highlightedBodies.begin(); it != highlightedBodies.end(); ++it)
    {
        if (*it != NULL)
            (*it)->Unhighlight();
    }
    highlightedBodies.clear();
}

void ZD_StraightLifterReview::WriteReport(const std::vector<std::string>& lines) const
{
    NXOpen::ListingWindow* listingWindow = theSession->ListingWindow();
    listingWindow->Open();
    listingWindow->WriteLine("========== 直顶头审查 ==========");
    for (std::vector<std::string>::const_iterator it = lines.begin(); it != lines.end(); ++it)
        listingWindow->WriteLine(*it);
    listingWindow->WriteLine("================================");
}

void ZD_StraightLifterReview::ReviewBody(NXOpen::Body* body, double radiusLimit)
{
    const double minSideAngle = 3.0;
    const double minHeight = 30.0;
    const double angleTolerance = 0.1;
    const int planarFaceType = 22;
    const int cylindricalFaceType = 16;

    double bodyBox[6] = {0.0};
    if (UF_MODL_ask_bounding_box(body->Tag(), bodyBox) != 0)
        throw NXOpen::NXException::Create(1, "无法读取所选实体的包围盒。");

    const double zMin = bodyBox[2];
    const double zMax = bodyBox[5];
    const double height = zMax - zMin;
    std::vector<NXOpen::Face*> sideFaces;
    std::vector<double> sideAngles;
    std::vector<double> sideOutwardNormalZ;
    std::vector<NXOpen::Face*> failedFaces;
    NXOpen::Face* bottomFace = NULL;
    double bottomNormalZ = 0.0;
    double bottomZ = 1.0e100;
    std::vector<std::string> report;

    std::ostringstream bodyLine;
    bodyLine << "审查实体 Tag " << body->Tag();
    report.push_back(bodyLine.str());

    std::ostringstream heightLine;
    heightLine << std::fixed << std::setprecision(3)
               << "[R2] Z 向高度=" << height << " mm，标准 >= " << minHeight << " mm："
               << (height >= minHeight ? "通过。" : "失败。");
    report.push_back(heightLine.str());
    if (height < minHeight)
    {
        body->Highlight();
        highlightedBodies.push_back(body);
        NXOpen::Part* workPart = theSession->Parts()->Work();
        if (workPart != NULL)
        {
            std::vector<NXOpen::IFitTo*> fitObjects;
            fitObjects.push_back(body);
            NXOpen::ModelingView* workView = workPart->ModelingViews()->WorkView();
            workView->FitToObjects(fitObjects);
            workView->UpdateDisplay();
        }

        std::ostringstream heightWarning;
        heightWarning << "直顶高度不够，无法正常放下直顶杆。\n"
                      << "当前直顶头 Tag：" << body->Tag()
                      << "\n关闭本窗口后将继续检查下一个实体。";
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show(
            "直顶头审查",
            NXOpen::NXMessageBox::DialogTypeWarning,
            heightWarning.str());
    }

    const std::vector<NXOpen::Face*> faces = body->GetFaces();
    for (std::vector<NXOpen::Face*>::const_iterator it = faces.begin(); it != faces.end(); ++it)
    {
        NXOpen::Face* face = *it;
        int type = 0;
        int normalDirection = 0;
        double point[3] = {0.0};
        double direction[3] = {0.0};
        double faceBox[6] = {0.0};
        double radius = 0.0;
        double radiusData = 0.0;
        if (UF_MODL_ask_face_data(face->Tag(), &type, point, direction, faceBox, &radius, &radiusData, &normalDirection) != 0)
            continue;

        if (type == planarFaceType)
        {
            const double angle = AngleToZDegrees(direction[2]);
            // 底面必须先是接近水平的端面候选；侧面即使延伸到最低 Z，也不能作为底面。
            if (angle >= 60.0 && faceBox[2] < bottomZ)
            {
                bottomZ = faceBox[2];
                bottomFace = face;
                bottomNormalZ = direction[2];
            }

            if (angle <= 30.0)
            {
                sideFaces.push_back(face);
                sideAngles.push_back(angle);

                const double bodyCenterX = (bodyBox[0] + bodyBox[3]) * 0.5;
                const double bodyCenterY = (bodyBox[1] + bodyBox[4]) * 0.5;
                const double faceCenterX = (faceBox[0] + faceBox[3]) * 0.5;
                const double faceCenterY = (faceBox[1] + faceBox[4]) * 0.5;
                const double horizontalLength = std::sqrt(direction[0] * direction[0] + direction[1] * direction[1]);
                const double outwardX = faceCenterX - bodyCenterX;
                const double outwardY = faceCenterY - bodyCenterY;
                const double outwardLength = std::sqrt(outwardX * outwardX + outwardY * outwardY);
                double outwardAlignment = 0.0;
                if (horizontalLength > 1.0e-12 && outwardLength > 1.0e-12)
                    outwardAlignment = (direction[0] * outwardX + direction[1] * outwardY) / (horizontalLength * outwardLength);
                sideOutwardNormalZ.push_back(outwardAlignment >= 0.0 ? direction[2] : -direction[2]);

                if (angle + 1.0e-6 < minSideAngle)
                    failedFaces.push_back(face);
            }
        }

        if (radiusLimit > 0.0 && type == cylindricalFaceType && radius + 1.0e-6 < radiusLimit)
        {
            failedFaces.push_back(face);
            std::ostringstream line;
            line << std::fixed << std::setprecision(3)
                 << "[R9] 圆角面 Tag " << face->Tag() << " 半径=" << radius
                 << " mm，小于输入标准 " << radiusLimit << " mm：失败，已标红。";
            report.push_back(line.str());
        }
    }

    if (sideFaces.size() != 4)
    {
        std::ostringstream line;
        line << "[R1] 主侧面识别失败：候选面数量=" << sideFaces.size() << "，预期为 4。";
        report.push_back(line.str());
    }
    else
    {
        for (std::size_t index = 0; index < sideFaces.size(); ++index)
        {
            std::ostringstream line;
            line << std::fixed << std::setprecision(3)
                 << "[R1] 侧面 Tag " << sideFaces[index]->Tag() << " 与 Z 轴夹角="
                 << sideAngles[index] << "°，标准 >= " << minSideAngle << "°："
                 << (sideAngles[index] >= minSideAngle ? "通过。" : "失败，已标红。");
            report.push_back(line.str());
        }
    }

    if (sideOutwardNormalZ.size() != 4)
        report.push_back("[R4] 主侧面识别失败，无法检查拔模角正负方向。");
    else
    {
        for (std::size_t index = 0; index < sideFaces.size(); ++index)
        {
            const double clampedNormalZ = (std::max)(-1.0, (std::min)(1.0, sideOutwardNormalZ[index]));
            const double signedDraftAngle = std::asin(clampedNormalZ) * 180.0 / 3.14159265358979323846;
            std::ostringstream line;
            line << std::fixed << std::setprecision(3)
                 << "[R4] 侧面 Tag " << sideFaces[index]->Tag()
                 << " 相对 +Z 的拔模角=" << signedDraftAngle << "°，";
            if (signedDraftAngle > 1.0e-6)
            {
                line << "为正数：失败，已标红。";
                failedFaces.push_back(sideFaces[index]);
            }
            else
                line << "不是正数：通过。";
            report.push_back(line.str());
        }
    }

    if (bottomFace != NULL)
    {
        const double normalAngle = 90.0 - AngleToZDegrees(bottomNormalZ);
        std::ostringstream line;
        line << std::fixed << std::setprecision(3)
             << "[R3] 底面 Tag " << bottomFace->Tag() << " 与 Z 轴夹角="
             << (90.0 - normalAngle) << "°，标准 90.000°±" << angleTolerance << "°：";
        if (normalAngle > angleTolerance)
        {
            line << "失败，已标红。";
            failedFaces.push_back(bottomFace);
        }
        else
            line << "通过。";
        report.push_back(line.str());
    }
    else
        report.push_back("[R3] 未识别到底面，无法检查底面垂直度。");

    if (radiusLimit <= 0.0)
        report.push_back("[R9] 半径输入为 0 mm，已跳过圆角审查。");

    std::sort(failedFaces.begin(), failedFaces.end());
    failedFaces.erase(std::unique(failedFaces.begin(), failedFaces.end()), failedFaces.end());
    for (std::vector<NXOpen::Face*>::const_iterator it = failedFaces.begin(); it != failedFaces.end(); ++it)
        HighlightFace(*it);

    std::ostringstream summary;
    summary << "审查完成：标红错误面 " << failedFaces.size() << " 个。";
    report.push_back(summary.str());
    WriteReport(report);
}
//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int ZD_StraightLifterReview::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == body_select)
        {
        //---------Enter your code here-----------
        }
        else if(block == radius_dim0)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int ZD_StraightLifterReview::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
        if (errorCode == 0)
            CommitReviewDisplay();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        ZD_StraightLifterReview::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* ZD_StraightLifterReview::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}












